In [1]:
import numpy as np

In [2]:
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30))
a=array1.reshape((5, 6))
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [3]:
#2.呈上題的array，找出被6除餘1的數的索引
np.where(a/(6%1))

<ipython-input-3-34799206557b>:2: RuntimeWarning: divide by zero encountered in true_divide
  np.where(a/(6%1))
<ipython-input-3-34799206557b>:2: RuntimeWarning: invalid value encountered in true_divide
  np.where(a/(6%1))


(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
        3, 3, 4, 4, 4, 4, 4, 4], dtype=int64),
 array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3,
        4, 5, 0, 1, 2, 3, 4, 5], dtype=int64))